//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePsychologist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePsychologist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz zmienić dane?.
        /// </summary>
        public static string AskForConfirmation {
            get {
                return ResourceManager.GetString("AskForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data urodzenia.
        /// </summary>
        public static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string ConfrimLabel {
            get {
                return ResourceManager.GetString("ConfrimLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schizofrenia.
        /// </summary>
        public static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83.230.14.31.
        /// </summary>
        public static string DB_HOST {
            get {
                return ResourceManager.GetString("DB_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestwaifugabi.
        /// </summary>
        public static string DB_PASS {
            get {
                return ResourceManager.GetString("DB_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345.
        /// </summary>
        public static string DB_PORT {
            get {
                return ResourceManager.GetString("DB_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string DB_USER {
            get {
                return ResourceManager.GetString("DB_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnoza.
        /// </summary>
        public static string DiagnosisLabel {
            get {
                return ResourceManager.GetString("DiagnosisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj dane osobowe.
        /// </summary>
        public static string EditDataLabel {
            get {
                return ResourceManager.GetString("EditDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogOutLabel {
            get {
                return ResourceManager.GetString("LogOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODUŁ PACJENTA.
        /// </summary>
        public static string PatientLabel1 {
            get {
                return ResourceManager.GetString("PatientLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobieta.
        /// </summary>
        public static string SexKobieta {
            get {
                return ResourceManager.GetString("SexKobieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płeć.
        /// </summary>
        public static string SexLabel {
            get {
                return ResourceManager.GetString("SexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mężczyzna.
        /// </summary>
        public static string SexMezczyzna {
            get {
                return ResourceManager.GetString("SexMezczyzna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
    }
}
